name: orion_cx
version: 1.0.0+1
publish_to: 'none'
description: Protótipo funcional em Flutter para os fluxos conversacionais Orion CX.

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
